import { OrdersProps } from "../sample-data/orders";
import { ProfileProps } from "../sample-data/profile";

export type RootStackParamList = {
  splash: undefined;
  "first-onboarding": undefined;
  "second-onboarding": undefined;
  "third-onboarding": undefined;
  "fourth-onboarding": undefined;
  "fifth-onboarding": undefined;
  "sixth-onboarding": undefined;
  "forgot-password": undefined;
  "reset-password": undefined;
  "email-verification": undefined;
  "otp-verification": undefined;
  "electricity-provider": undefined;
  "order-details": any;
  "items-page": any;
  "item-details": any;
  login: undefined;
  signup: undefined;
  home: undefined;
  accessories: undefined;
  orders: undefined;
  profile: undefined;
  gas: undefined;
  petroleum: undefined;
  diesel: undefined;
  cart: undefined;
  complaints: undefined;
  referral: any;
  "user-wallet": any;
  "user-details": any;
  favourite: any;
  "user-address": any;
  "user-payment": any;
  "item-suggestion": any;
  help: any;
  contact: any;
  "diesel-details": any;
  "gas-details": any;
  chat: { orderDetails: OrdersProps; target: 'rider' | 'vendor' };
  "profile-details": { orderDetails: OrdersProps; target: 'rider' | 'vendor' };
  "update-form": { profileDetails: ProfileProps; target: 'name' | 'username' | 'birthday' };
  "payment-result": { result: 'successful' | 'unsuccessful' };
  transfer: { amount: number };
  card: { amount: number };
  electricity: any;
  Main: undefined;
  settings: undefined;
};
