export type RootStackParamList = {
  splash: undefined;
  "first-onboarding": undefined;
  "second-onboarding": undefined;
  "third-onboarding": undefined;
  "fourth-onboarding": undefined;
  "fifth-onboarding": undefined;
  "sixth-onboarding": undefined;
  "forgot-password": undefined;
  "reset-password": undefined;
  "email-verification": undefined;
  "otp-verification": undefined;
  "electricity-provider": undefined;
  "order-details": any;
  login: undefined;
  signup: undefined;
  home: undefined;
  accessories: undefined;
  orders: undefined;
  profile: undefined;
  gas: undefined;
  petroleum: undefined;
  diesel: undefined;
  electricity: any;
  Main: undefined;
  settings: undefined;
};
