import {GasProps} from '../sample-data/gas';
import {DetailsProps} from '../sample-data/home';
import {OrdersProps} from '../sample-data/orders';
import {ProfileProps} from '../sample-data/profile';

export type RootStackParamList = {
  splash: undefined;
  'first-onboarding': undefined;
  'second-onboarding': undefined;
  'third-onboarding': undefined;
  'fourth-onboarding': undefined;
  'fifth-onboarding': undefined;
  'sixth-onboarding': undefined;
  'forgot-password': undefined;
  'reset-password': undefined;
  'email-verification': undefined;
  'otp-verification': undefined;
  'electricity-provider': undefined;
  'order-details': {orderDetails: OrdersProps};
  'deliver-details': any;
  'gas-order-details': {gasDetails: DetailsProps; selectedCylinder: GasProps};
  'items-page': any;
  'item-details': any;
  login: undefined;
  signup: undefined;
  home: undefined;
  accessories: undefined;
  orders: undefined;
  profile: undefined;
  gas: any;
  petroleum: any;
  diesel: any;
  cart: undefined;
  complaints: undefined;
  referral: any;
  delivery: {orderDetails: OrdersProps};
  'user-wallet': any;
  'user-details': any;
  favourite: any;
  'user-address': any;
  'user-payment': any;
  'item-suggestion': any;
  'gas-checkout': {gasDetails: DetailsProps; selectedCylinder: GasProps};
  help: any;
  contact: any;
  'diesel-details': any;
  'gas-details': any;
  'change-address': any;
  'default-card': {result: 'successful' | 'unsuccessful'};
  'report-result': {
    orderDetails: OrdersProps;
    result: 'successful' | 'unsuccessful';
    target: 'rider' | 'vendor';
  };
  chat: {orderDetails: OrdersProps; target: 'rider' | 'vendor'};
  'profile-details': {orderDetails: OrdersProps; target: 'rider' | 'vendor'};
  report: {orderDetails: OrdersProps; target: 'rider' | 'vendor'};
  'update-form': {
    profileDetails: ProfileProps;
    target: 'name' | 'username' | 'birthday' | 'email';
  };
  'help-options': {
    profileDetails: ProfileProps;
    target: 'faq' | 'user-policy' | 'rating' | 'share';
  };
  'payment-result': {result: 'successful' | 'unsuccessful'};
  transfer: {amount: number};
  card: {amount: number};
  electricity: any;
  Main: undefined;
  settings: undefined;
};
