interface Country {
  dialCode: string;
  country: string;
  flag: string;
}

export const countries: Country[] = [
  { country: 'Afghanistan', dialCode: '+93', flag: '🇦🇫' },
  { country: 'Albania', dialCode: '+355', flag: '🇦🇱' },
  { country: 'Algeria', dialCode: '+213', flag: '🇩🇿' },
  { country: 'Andorra', dialCode: '+376', flag: '🇦🇩' },
  { country: 'Angola', dialCode: '+244', flag: '🇦🇴' },
  { country: 'Argentina', dialCode: '+54', flag: '🇦🇷' },
  { country: 'Armenia', dialCode: '+374', flag: '🇦🇲' },
  { country: 'Australia', dialCode: '+61', flag: '🇦🇺' },
  { country: 'Austria', dialCode: '+43', flag: '🇦🇹' },
  { country: 'Azerbaijan', dialCode: '+994', flag: '🇦🇿' },
  { country: 'Bahamas', dialCode: '+1-242', flag: '🇧🇸' },
  { country: 'Bahrain', dialCode: '+973', flag: '🇧🇭' },
  { country: 'Bangladesh', dialCode: '+880', flag: '🇧🇩' },
  { country: 'Barbados', dialCode: '+1-246', flag: '🇧🇧' },
  { country: 'Belarus', dialCode: '+375', flag: '🇧🇾' },
  { country: 'Belgium', dialCode: '+32', flag: '🇧🇪' },
  { country: 'Belize', dialCode: '+501', flag: '🇧🇿' },
  { country: 'Benin', dialCode: '+229', flag: '🇧🇯' },
  { country: 'Bhutan', dialCode: '+975', flag: '🇧🇹' },
  { country: 'Bolivia', dialCode: '+591', flag: '🇧🇴' },
  { country: 'Botswana', dialCode: '+267', flag: '🇧🇼' },
  { country: 'Brazil', dialCode: '+55', flag: '🇧🇷' },
  { country: 'Bulgaria', dialCode: '+359', flag: '🇧🇬' },
  { country: 'Burkina Faso', dialCode: '+226', flag: '🇧🇫' },
  { country: 'Burundi', dialCode: '+257', flag: '🇧🇮' },
  { country: 'Cambodia', dialCode: '+855', flag: '🇰🇭' },
  { country: 'Cameroon', dialCode: '+237', flag: '🇨🇲' },
  { country: 'Canada', dialCode: '+1', flag: '🇨🇦' },
  { country: 'Chad', dialCode: '+235', flag: '🇹🇩' },
  { country: 'Chile', dialCode: '+56', flag: '🇨🇱' },
  { country: 'China', dialCode: '+86', flag: '🇨🇳' },
  { country: 'Colombia', dialCode: '+57', flag: '🇨🇴' },
  { country: 'Congo', dialCode: '+242', flag: '🇨🇬' },
  { country: 'Costa Rica', dialCode: '+506', flag: '🇨🇷' },
  { country: 'Croatia', dialCode: '+385', flag: '🇭🇷' },
  { country: 'Cuba', dialCode: '+53', flag: '🇨🇺' },
  { country: 'Cyprus', dialCode: '+357', flag: '🇨🇾' },
  { country: 'Czech Republic', dialCode: '+420', flag: '🇨🇿' },
  { country: 'Denmark', dialCode: '+45', flag: '🇩🇰' },
  { country: 'Djibouti', dialCode: '+253', flag: '🇩🇯' },
  { country: 'Ecuador', dialCode: '+593', flag: '🇪🇨' },
  { country: 'Egypt', dialCode: '+20', flag: '🇪🇬' },
  { country: 'France', dialCode: '+33', flag: '🇫🇷' },
  { country: 'Germany', dialCode: '+49', flag: '🇩🇪' },
  { country: 'Ghana', dialCode: '+233', flag: '🇬🇭' },
  { country: 'India', dialCode: '+91', flag: '🇮🇳' },
  { country: 'Japan', dialCode: '+81', flag: '🇯🇵' },
  { country: 'Kenya', dialCode: '+254', flag: '🇰🇪' },
  { country: 'Mexico', dialCode: '+52', flag: '🇲🇽' },
  { country: 'Nigeria', dialCode: '+234', flag: '🇳🇬' },
  { country: 'Russia', dialCode: '+7', flag: '🇷🇺' },
  { country: 'South Africa', dialCode: '+27', flag: '🇿🇦' },
  { country: 'Spain', dialCode: '+34', flag: '🇪🇸' },
  { country: 'Turkey', dialCode: '+90', flag: '🇹🇷' },
  { country: 'United Kingdom', dialCode: '+44', flag: '🇬🇧' },
  { country: 'United States', dialCode: '+1', flag: '🇺🇸' },
  { country: 'Vietnam', dialCode: '+84', flag: '🇻🇳' },
  { country: 'Zambia', dialCode: '+260', flag: '🇿🇲' },
  { country: 'Zimbabwe', dialCode: '+263', flag: '🇿🇼' }
];
